### ISSUE TITLE
Find Electrical Dimensions Here

### ISSUE THREAD

**Issue by JacobLoufek** [usfsoar/NSL_23-24_PayloadMech#25]
Ask Alvaro for dimensions and list of each electrical component on the drone. 

Flight Controller 
ESCs
Drone Module

How many different components are there

**Comment by kpshum** [comment]
https://docs.google.com/spreadsheets/d/1YsuRco_jQiQ7ysE-41C9JWDJeEHuIT69c4P6P3Fa9p8/edit?usp=sharing
Here's the spreadsheet for all the components, I have been making boxes in CAD of the dimensions purely by their measurement with no design. Right now we are trying to assess not only where generally these components will be placed on the drone itself, but what range of dimensions we have for our unknown components once all the boxes are placed. I still need to work more with Lucas and others to figure out the general layout we have so that the placements can be more useful rather than just approximating their position. Anyone please lmk if you want to work on this with me or have questions about this.
